<x-filament-panels::page>
    <div class="grid gap-4 2xl:grid-cols-[460px_1fr]">
        <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-800 dark:bg-gray-900">
            <h3 class="text-base font-semibold text-gray-950 dark:text-white">{{ $editandoId ? 'Editar atencion' : 'Nueva atencion diaria' }}</h3>
            <form wire:submit.prevent="guardar" class="mt-4 space-y-3">
                <div class="grid gap-2 sm:grid-cols-2"><input type="date" wire:model="fecha" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><select wire:model.live="pacienteId" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Buscar paciente existente</option>@foreach ($this->pacientes as $p)<option value="{{ $p->id }}">{{ $p->nombres }}</option>@endforeach</select></div>
                <input wire:model="nombres" placeholder="Paciente / colaborador" class="block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white">
                <div class="grid gap-2 sm:grid-cols-3"><input type="number" wire:model="edad" placeholder="Edad" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input wire:model="area" list="areas" placeholder="Area" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input wire:model="cargo" list="cargos" placeholder="Cargo" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"></div>
                <div class="grid gap-2 sm:grid-cols-2"><select wire:model="certificados" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Certificado</option>@foreach ($this->catalogo('certificado_medico') as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select wire:model="subsidio" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Subsidio</option>@foreach ($this->catalogo('subsidio') as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select></div>
                <div class="grid gap-2 sm:grid-cols-4"><input type="number" step="0.5" wire:model="horas_certificado" placeholder="Horas" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="number" wire:model="dias_certificado" placeholder="Dias" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="date" wire:model="fecha_inicio_certificado" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="date" wire:model="fecha_fin_certificado" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"></div>
                <input wire:model="medico_certifica" placeholder="Medico que certifica" class="block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white">
                <div class="grid gap-2 sm:grid-cols-2"><select wire:model="causa" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Causa</option>@foreach ($this->catalogo('causa') as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><input wire:model="diagnostico" list="diagnosticos" placeholder="Diagnostico" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"></div>

                <div class="rounded-xl border border-violet-100 bg-violet-50/40 p-3 dark:border-violet-900 dark:bg-violet-950/20">
                    <div class="mb-2 flex items-center justify-between"><span class="text-xs font-semibold uppercase tracking-wide text-violet-700 dark:text-violet-300">Medicacion entregada</span><button type="button" wire:click="agregarMedicamento" class="text-xs font-semibold text-violet-700">Agregar</button></div>
                    <div class="space-y-2">
                        @foreach ($medicamentos as $i => $m)
                            <div class="grid gap-2 sm:grid-cols-[1fr_80px_36px]">
                                <select wire:model="medicamentos.{{ $i }}.producto_id" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white" required><option value="">Seleccionar producto...</option>@foreach ($this->productos as $p)<option value="{{ $p->id }}">{{ $p->nombre }} ({{ $p->tipo }})</option>@endforeach</select>
                                <input type="number" step="0.01" wire:model="medicamentos.{{ $i }}.cantidad" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white" min="0.01">
                                <button type="button" wire:click="quitarMedicamento({{ $i }})" class="rounded-lg border border-gray-200 text-sm dark:border-gray-700">x</button>
                            </div>
                        @endforeach
                    </div>
                </div>

                <textarea wire:model="observacion" rows="3" placeholder="Observacion" class="block w-full rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"></textarea>
                <div class="flex gap-2"><button class="rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold text-white">Guardar atencion</button><button type="button" wire:click="limpiarFormulario" class="rounded-lg border border-gray-200 px-4 py-2 text-sm dark:border-gray-700">Limpiar</button></div>
            </form>
        </section>

        <section class="rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
            <div class="border-b border-gray-100 px-5 py-4 dark:border-gray-800"><h3 class="font-semibold text-gray-950 dark:text-white">Atenciones registradas</h3><div class="mt-3 grid gap-2 sm:grid-cols-5"><input type="date" wire:model.live="desde" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="date" wire:model.live="hasta" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input wire:model.live.debounce.400ms="buscar" placeholder="Buscar" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><select wire:model.live="areaFiltro" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Area</option>@foreach ($this->catalogo('area') as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select><select wire:model.live="causaFiltro" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><option value="">Causa</option>@foreach ($this->catalogo('causa') as $v)<option value="{{ $v }}">{{ $v }}</option>@endforeach</select></div></div>
            <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-950/50"><tr><th class="px-5 py-3 text-left text-xs text-gray-500">Fecha / Paciente</th><th class="px-5 py-3 text-left text-xs text-gray-500">Atencion</th><th class="px-5 py-3 text-left text-xs text-gray-500">Medicacion</th><th class="px-5 py-3 text-right text-xs text-gray-500">Acciones</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach ($this->partes as $p)<tr><td class="px-5 py-3"><p class="font-medium text-gray-900 dark:text-white">{{ $p->nombres }}</p><p class="text-xs text-gray-500">{{ $p->fecha?->format('d/m/Y') }} · {{ $p->area }} · {{ $p->cargo }}</p></td><td class="px-5 py-3"><p class="text-gray-700 dark:text-gray-300">{{ $p->causa ?: '-' }}</p><p class="max-w-md truncate text-xs text-gray-500">{{ $p->diagnostico }}</p>@if($p->certificados && $p->certificados !== 'SIN CERTIFICADO')<span class="mt-1 inline-flex rounded-full bg-orange-50 px-2 py-0.5 text-xs text-orange-700">{{ $p->certificados }}</span>@endif</td><td class="px-5 py-3"><div class="flex flex-wrap gap-1">@foreach ($p->medicamentos as $m)<span class="rounded-full bg-violet-50 px-2 py-0.5 text-xs text-violet-700">{{ $m->producto?->nombre ?? $m->nombre_original }} x {{ $m->cantidad }}</span>@endforeach</div></td><td class="px-5 py-3 text-right"><button wire:click="editar({{ $p->id }})" class="text-sky-600 hover:underline">Editar</button><button wire:click="eliminar({{ $p->id }})" wire:confirm="Eliminar esta atencion?" class="ml-3 text-red-600 hover:underline">Eliminar</button></td></tr>@endforeach</tbody></table></div>
        </section>
    </div>

    <datalist id="areas">@foreach ($this->catalogo('area') as $v)<option value="{{ $v }}">@endforeach</datalist>
    <datalist id="cargos">@foreach ($this->catalogo('cargo') as $v)<option value="{{ $v }}">@endforeach</datalist>
    <datalist id="diagnosticos">@foreach ($this->catalogo('diagnostico') as $v)<option value="{{ $v }}">@endforeach</datalist>
</x-filament-panels::page>
