<x-filament-panels::page>
    <div class="space-y-4">
        <section class="rounded-2xl border border-violet-200 bg-white p-5 shadow-sm dark:border-violet-900 dark:bg-gray-900">
            <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
                <div><h3 class="text-base font-semibold text-gray-950 dark:text-white">Generar Kardex mensual</h3><p class="text-sm text-gray-500">Cierre por mes calendario o rango personalizado desde/hasta.</p></div>
                <div class="grid gap-2 sm:grid-cols-5"><input type="month" wire:model="mes" wire:change="aplicarMes" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="date" wire:model="desde" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><input type="date" wire:model="hasta" class="rounded-lg border-gray-300 text-sm dark:border-gray-700 dark:bg-gray-950 dark:text-white"><button wire:click="generar" class="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Generar</button><button wire:click="cerrar" class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-gray-900">Cerrar</button></div>
            </div>
        </section>

        @if ($this->cierre)
            <section class="rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
                <div class="flex items-center justify-between gap-3 border-b border-gray-100 px-5 py-4 dark:border-gray-800"><div><h3 class="font-semibold text-gray-950 dark:text-white">Kardex {{ $this->cierre->fecha_inicio->format('d/m/Y') }} - {{ $this->cierre->fecha_fin->format('d/m/Y') }}</h3><p class="text-xs text-gray-500">Estado: {{ $this->cierre->estado }} · {{ $this->cierre->items->count() }} items</p></div><div class="flex gap-2"><button wire:click="exportar" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Exportar Excel</button>@if($this->cierre->estado === 'cerrado')<button wire:click="reabrir({{ $this->cierre->id }})" class="rounded-lg border border-gray-200 px-3 py-2 text-xs font-semibold">Reabrir</button>@endif</div></div>
                <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-950/50"><tr><th class="px-5 py-3 text-left text-xs text-gray-500">Producto</th><th class="px-5 py-3 text-right text-xs text-gray-500">Saldo ant.</th><th class="px-5 py-3 text-right text-xs text-gray-500">Ingresos</th><th class="px-5 py-3 text-right text-xs text-gray-500">Egresos</th><th class="px-5 py-3 text-right text-xs text-gray-500">Total</th><th class="px-5 py-3 text-left text-xs text-gray-500">Caducidad</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach ($this->cierre->items as $item)<tr><td class="px-5 py-3 font-medium text-gray-900 dark:text-white">{{ $item->nombre }}<p class="text-xs text-gray-500">{{ $item->tipo }}</p></td><td class="px-5 py-3 text-right">{{ number_format($item->saldo_anterior, 2, ',', '.') }}</td><td class="px-5 py-3 text-right text-emerald-600">{{ number_format($item->ingresos, 2, ',', '.') }}</td><td class="px-5 py-3 text-right text-red-600">{{ number_format($item->egresos, 2, ',', '.') }}</td><td class="px-5 py-3 text-right font-semibold">{{ number_format($item->total, 2, ',', '.') }}</td><td class="px-5 py-3 text-gray-500">{{ $item->fecha_caducidad?->format('d/m/Y') ?: '-' }}</td></tr>@endforeach</tbody></table></div>
            </section>
        @endif

        @if ($this->cierres->isNotEmpty())
            <section class="rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900"><div class="border-b border-gray-100 px-5 py-4 dark:border-gray-800"><h3 class="font-semibold text-gray-950 dark:text-white">Historico de cierres</h3></div><div class="grid gap-2 p-4 sm:grid-cols-2 lg:grid-cols-4">@foreach($this->cierres as $c)<button wire:click="$set('cierreId', {{ $c->id }})" class="rounded-xl border border-gray-100 p-3 text-left hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-gray-950"><p class="font-medium text-gray-900 dark:text-white">{{ $c->fecha_inicio->format('d/m/Y') }} - {{ $c->fecha_fin->format('d/m/Y') }}</p><p class="text-xs text-gray-500">{{ $c->estado }} · {{ $c->items_count }} items</p></button>@endforeach</div></section>
        @endif
    </div>
</x-filament-panels::page>
